version: '3.8'
services:
  postgresql:
    image: postgres:14.5
    container_name: payment_database
    environment:
      POSTGRES_DB: payment
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    ports:
      - "9000:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:  {}